//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverReview
    {
        public int ReviewCode { get; set; }
        public string Review { get; set; }
        public int DriverReviewCode { get; set; }
        public int UserId { get; set; }
    
        public virtual RegularUser RegularUser { get; set; }
        public virtual TaxiDriver TaxiDriver { get; set; }
    }
}
