//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxiDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxiDriver()
        {
            this.RegularUsers = new HashSet<RegularUser>();
            this.DriverReviews = new HashSet<DriverReview>();
            this.Travels = new HashSet<Travel>();
        }
    
        public int DriverId { get; set; }
        public string DriverName { get; set; }
        public string PelephoneDriverNumber { get; set; }
        public int VehicleTaxiCode { get; set; }
        public double CurrentLocationLat { get; set; }
        public double CurrentLocationLng { get; set; }
        public string ImageDriver { get; set; }
        public Nullable<int> StationCode { get; set; }
        public int Prioritys { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularUser> RegularUsers { get; set; }
        public virtual TaxiStation TaxiStation { get; set; }
        public virtual Taxi Taxi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverReview> DriverReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travel> Travels { get; set; }
    }
}
