//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int TravelCode { get; set; }
        public int UserId { get; set; }
        public double StartingPointLat { get; set; }
        public double StartingPointLng { get; set; }
        public double DestinatiPnpointLat { get; set; }
        public double DestinatiPnpointLng { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public double FixedPrice { get; set; }
        public int DayInTheWeek { get; set; }
        public bool PriorityTime { get; set; }
        public bool PriorityPrice { get; set; }
        public int PriorityDriverCode { get; set; }
    
        public virtual RegularUser RegularUser { get; set; }
        public virtual TaxiDriver TaxiDriver { get; set; }
    }
}
